- name: Deploy NetEye stack on all popsites
  hosts: popsites
  become: true
  gather_facts: true

  pre_tasks:
    - name: Check if Docker is installed
      ansible.builtin.command: which docker
      register: docker_check
      ignore_errors: true

    - name: Set fact if Docker is missing
      ansible.builtin.set_fact:
        docker_not_installed: "{{ docker_check.rc != 0 }}"

  roles:
    - role: docker
      when: docker_not_installed

    - role: popsites
